# Generated by Django 3.1.3 on 2020-11-09 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('58266fe4-f1b3-4061-ab3e-139f9e5a0fcd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
