# Generated by Django 3.1.3 on 2020-11-09 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201109_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('685bd5b5-b005-4ef4-af97-4d45332ee1de'), editable=False, primary_key=True, serialize=False),
        ),
    ]
