# Generated by Django 3.1.3 on 2020-11-27 05:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201127_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('04021ee1-29f5-4828-b3f5-ba16b45ca8a5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
