# Generated by Django 3.1.3 on 2020-11-05 08:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('examinee_id', models.UUIDField()),
                ('exam_id', models.UUIDField()),
                ('module_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alert', models.BooleanField(default=False)),
                ('description', models.CharField(default=None, max_length=200, null=True)),
                ('content', models.CharField(default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
