# Generated by Django 3.1.3 on 2020-11-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent_messages', '0002_auto_20201109_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='exam_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='examinee_id',
            field=models.UUIDField(),
        ),
    ]
